name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  auth-service:
    name: Auth service
    timeout-minutes: 15
    runs-on: ubuntu-latest
    outputs:
      auth-service-function-name: ${{ steps.release.outputs.auth-service-function-name }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Pulumi
        uses: pulumi/actions@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Release
        id: release
        run: |
          yarn deploy --filter=auth-service-infra
          AUTH_SERVICE_FUNCTION_NAME=$(pulumi stack output someRandomOutput)
          echo "auth-service-function-name=$AUTH_SERVICE_FUNCTION_NAME" >> "$GITHUB_OUTPUT"

    #      - name: Test
    #        run: yarn test


  docs-app:
    name: Docs app
    needs:
      - auth-service
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Cache turbo build setup
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Release
        env:
          WWW_ARTIFACTS: ${{needs.auth-service.outputs.auth-service-function-name}}
        run: yarn deploy --filter=docs

#      - name: Test
#        run: yarn test